### PR TITLE
Switch to 2019/20

### PR DESCRIPTION
**Pull request by rboyatt**
I was considering extending the plugin to include 'nearest double not done' (or similar) - it would need this switch to 19/20 data.

### CODE REVIEW

**Comment by fraz3alpha** [comment]
Ah yes! It's time to start collecting the Christmas data, that's for the prod!

It was all a bit rushed last year, maybe this year it can be done in a more managed way. 

For reference, I don't want to overlap what we're putting on the running challenges site with other useful sites such as the double-finder - http://tailrun.uk/nyd/2019/ , or even the tourist tool really, it's best just to link out to those projects. So yes we can get this years data up, but I don't think we should be adding code to calculate distances or what doubles are possible etc.. best to leave people to use the other tools to explore :)

**Comment by rboyatt** [comment]
No problem for the prompt :)

Fair enough and completely understandable on overlapping with other tools.  I didn't get around to it in the end anyway.  Just an idle conversation about doubles that were walking/running/cycling distance apart!

**Comment by rboyatt** [comment]
Closing pull request - I think this redundant now.

**Comment by fraz3alpha** [comment]
I'm working on this evening under https://github.com/fraz3alpha/running-challenges/pull/196, it's turned out to be a fair bit of work with the geo.xml > events.json migration, and then a few other problems I've found along the way!

Really hoping the map will be correct for this year by the time I go to bed :)

**Comment by rboyatt** [comment]
I can see the commits going by - yes looks fun with the swap :-). Hope you can get it going before it's too late!  Happy to look at it tomorrow if you need another pair of eyes!

**Comment by fraz3alpha** [comment]
It's up! 

https://running-challenges.co.uk/map/

**Comment by fraz3alpha** [comment]
Performance is horrendous though :/

**Pull request closed without merging**
